-- 코드를 입력하세요
SELECT DISTINCT(ch. CAR_ID) 'CAR_ID'
FROM CAR_RENTAL_COMPANY_CAR cc join 
CAR_RENTAL_COMPANY_RENTAL_HISTORY ch USING(CAR_ID)
WHERE cc.CAR_TYPE IN ('세단') AND DATE_FORMAT(START_DATE, '%m')= 10 
ORDER BY ch.CAR_ID DESC